-- Seed test data for DB-backed card search.
-- Run after 001_init_binder_cards.sql

insert into public.expansions (
  id,
  name,
  series,
  total,
  printed_total,
  language,
  language_code,
  release_date,
  is_online_only
)
values (
  'base1',
  'Base',
  'Base',
  102,
  102,
  'English',
  'EN',
  '1999-01-09',
  false
)
on conflict (id) do update
set
  name = excluded.name,
  series = excluded.series,
  total = excluded.total,
  printed_total = excluded.printed_total,
  language = excluded.language,
  language_code = excluded.language_code,
  release_date = excluded.release_date,
  is_online_only = excluded.is_online_only,
  updated_at = now();

insert into public.cards (
  id,
  name,
  number,
  rarity,
  supertype,
  subtypes,
  types,
  rules,
  image_small,
  image_large,
  expansion_id,
  expansion_name,
  expansion_release_date,
  expansion_sort_order,
  language,
  language_code
)
values
  (
    'base1-4',
    'Charizard',
    '4',
    'Rare Holo',
    'Pokémon',
    array['Stage 2'],
    array['Fire'],
    array['As often as you like during your turn (before your attack), you may turn all Energy attached to Charizard into Fire Energy for the rest of the turn.'],
    'https://images.scrydex.com/pokemon/base1-4/small',
    'https://images.scrydex.com/pokemon/base1-4/large',
    'base1',
    'Base',
    '1999-01-09',
    4,
    'English',
    'EN'
  ),
  (
    'charizard-test-1',
    'Charizard',
    '006',
    'Rare Holo',
    'Pokémon',
    array['Stage 2'],
    array['Fire'],
    array[]::text[],
    'https://images.scrydex.com/pokemon/base1-4/small',
    'https://images.scrydex.com/pokemon/base1-4/large',
    'base1',
    'Base',
    '1999-01-09',
    6,
    'English',
    'EN'
  ),
  (
    'charizard-test-2',
    'Charizard',
    '007',
    'Rare',
    'Pokémon',
    array['Stage 2'],
    array['Fire'],
    array[]::text[],
    'https://images.scrydex.com/pokemon/base1-4/small',
    'https://images.scrydex.com/pokemon/base1-4/large',
    'base1',
    'Base',
    '1999-01-09',
    7,
    'English',
    'EN'
  ),
  (
    'charizard-test-3',
    'Charizard ex',
    '008',
    'Ultra Rare',
    'Pokémon',
    array['Stage 2', 'ex'],
    array['Fire'],
    array[]::text[],
    'https://images.scrydex.com/pokemon/base1-4/small',
    'https://images.scrydex.com/pokemon/base1-4/large',
    'base1',
    'Base',
    '1999-01-09',
    8,
    'English',
    'EN'
  ),
  (
    'charizard-test-4',
    'Dark Charizard',
    '009',
    'Rare Holo',
    'Pokémon',
    array['Stage 2'],
    array['Fire'],
    array[]::text[],
    'https://images.scrydex.com/pokemon/base1-4/small',
    'https://images.scrydex.com/pokemon/base1-4/large',
    'base1',
    'Base',
    '1999-01-09',
    9,
    'English',
    'EN'
  )
on conflict (id) do update
set
  name = excluded.name,
  number = excluded.number,
  rarity = excluded.rarity,
  supertype = excluded.supertype,
  subtypes = excluded.subtypes,
  types = excluded.types,
  rules = excluded.rules,
  image_small = excluded.image_small,
  image_large = excluded.image_large,
  expansion_id = excluded.expansion_id,
  expansion_name = excluded.expansion_name,
  expansion_release_date = excluded.expansion_release_date,
  expansion_sort_order = excluded.expansion_sort_order,
  language = excluded.language,
  language_code = excluded.language_code,
  updated_at = now();
